global:
  scrape_interval:     15s
  evaluation_interval: 15s

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
      # now the target server and monitor server are the same
      # usually they should be different servers
      # - targets: ['172.31.19.122:9100']